events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    # Using the local nameserver found in /etc/resolv.conf
    resolver 10.160.8.21 valid=30s;
    resolver_timeout 5s;

    server {
        listen 80;
        # Wildcard subdomain capture (e.g., <id>.127.0.0.1.sslip.io)
        server_name ~^(?<deploymentId>[^.]+)\.127\.0\.0\.1\.sslip\.io$;

        location / {
            # Define variables for S3 path
            set $s3_bucket "kritesh-vercel-clone-outputs.s3.ap-south-1.amazonaws.com";
            
            # Use proxy_pass to fetch from S3
            # If path is /, proxy to index.html
            set $path $uri;
            if ($path = "/") {
                set $path "/index.html";
            }

            proxy_pass https://$s3_bucket/deployments/$deploymentId$path;
            
            # Important Headers for S3
            proxy_set_header Host $s3_bucket;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_hide_header x-amz-id-2;
            proxy_hide_header x-amz-request-id;
            proxy_hide_header x-amz-meta-server-side-encryption;
            proxy_hide_header x-amz-server-side-encryption;
            proxy_hide_header x-amz-version-id;
            proxy_hide_header x-amz-storage-class;
            
            # Force success status codes for better SPA handling
            proxy_intercept_errors on;
            error_page 404 = /index.html;
        }
    }
}
